const INGREDIENTS={shell:[{name:'Crispy',emoji:'🥟',color:'#f7c948'},{name:'Soft',emoji:'🫓',color:'#f7a14d'},{name:'Mini',emoji:'🥮',color:'#ffd6a5'}],filling:[{name:'Potato',emoji:'🥔',color:'#c7d45d'},{name:'Ragda',emoji:'🫘',color:'#9adf7c'},{name:'Chickpea',emoji:'🫘',color:'#8cbf4b'}],water:[{name:'Mint',emoji:'🌿',color:'#68d87e'},{name:'Tamarind',emoji:'🍊',color:'#ff7b54'},{name:'Spicy',emoji:'🌶️',color:'#ef5d5d'}],topping:[{name:'Sev',emoji:'✨',color:'#ffd166'},{name:'Onion',emoji:'🧅',color:'#d7d2ff'},{name:'Coriander',emoji:'🌱',color:'#7ad49f'}]};const GROUPS=['shell','filling','water','topping'],LABELS={shell:'Shell',filling:'Filling',water:'Water',topping:'Topping'};const CUSTOMERS=[['😄','Asha','I want something minty!'],['😎','Ravi','Make it extra crispy!'],['🥳','Maya','Bring on the spice!'],['🤓','Arjun','Add all the toppings!'],['😋','Priya','A perfect plate, please!']];
const $=id=>document.getElementById(id),state={score:0,best:Number(localStorage.getItem('paniPuriBest')||0),level:1,combo:1,lives:3,time:60,order:null,selected:{},timer:null,started:false,over:false,sound:true,music:true,customerIndex:0};let audio=null,musicTimer=null;
function random(arr){return arr[Math.floor(Math.random()*arr.length)]}
function audioReady(){if(!audio){const C=window.AudioContext||window.webkitAudioContext;if(C)audio=new C()}if(audio&&audio.state==='suspended')audio.resume()}
function tone(f,d=.08,type='sine',g=.03){if(!state.sound)return;audioReady();if(!audio)return;const o=audio.createOscillator(),n=audio.createGain();o.type=type;o.frequency.value=f;n.gain.value=g;o.connect(n);n.connect(audio.destination);o.start();o.stop(audio.currentTime+d);n.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d)}
function musicLoop(){if(!state.music||!state.started)return;tone(261,.12,'triangle',.012);setTimeout(()=>tone(329,.12,'triangle',.012),150);setTimeout(()=>tone(392,.18,'triangle',.012),300);musicTimer=setTimeout(musicLoop,1300)}
function stopMusic(){clearTimeout(musicTimer)}
function buildIngredients(){const box=$('ingredients');box.innerHTML='';GROUPS.forEach(group=>{const section=document.createElement('div');section.className='group-box';section.innerHTML=`<h3>${LABELS[group]}</h3><div class="group-grid"></div>`;const grid=section.querySelector('.group-grid');INGREDIENTS[group].forEach(item=>{const b=document.createElement('button');b.className='ingredient-btn';b.dataset.group=group;b.dataset.name=item.name;b.innerHTML=`<span class="emoji">${item.emoji}</span><span>${item.name}</span>`;b.onclick=()=>{if(!state.started||state.over)return;state.selected[group]=item.name;tone(440,.08,'triangle',.02);refresh();renderPlate()};grid.appendChild(b)});box.appendChild(section)})}
function refresh(){document.querySelectorAll('.ingredient-btn').forEach(b=>b.classList.toggle('selected',state.selected[b.dataset.group]===b.dataset.name))}
function renderPlate(){const entries=GROUPS.filter(g=>state.selected[g]).map(g=>INGREDIENTS[g].find(x=>x.name===state.selected[g]));if(!entries.length){$('plate').innerHTML='<div class="plate-empty">No ingredients selected yet.</div>';return}$('plate').innerHTML=`<div class="plate-items">${entries.map(x=>`<div class="plate-item" title="${x.name}">${x.emoji}</div>`).join('')}</div>`}
function newOrder(){const order={};const isBoss=state.level>=3;GROUPS.forEach(g=>{let pool=INGREDIENTS[g];if(isBoss&&g==='water'){pool=INGREDIENTS[g].filter(i=>['Spicy','Mint'].includes(i.name));}order[g]=random(pool).name});if(isBoss&&Math.random()>.5){const spicy=INGREDIENTS['water'].find(i=>i.name==='Spicy');order.water=spicy.name}return order}
function renderCustomer(){const [emoji,name,line]=CUSTOMERS[state.customerIndex%CUSTOMERS.length];const bossMode=state.level>=3;const orderNumber=bossMode?`Boss Wave #${state.level}`:`#${state.customerIndex+1}`;$('customerNumber').textContent=orderNumber;$('customerCard').innerHTML=`<div class="avatar">${emoji}</div><h3>${name}'s Order</h3><div class="order-list">${GROUPS.map(g=>{const x=INGREDIENTS[g].find(i=>i.name===state.order[g]);return `<div class="order-chip"><span class="dot" style="background:${x.color}"></span>${x.name}</div>`}).join('')}</div>`;$('speechBubble').textContent=line;$('speechBubble').classList.remove('pop');void $('speechBubble').offsetWidth;$('speechBubble').classList.add('pop')}
function hud(){ $('score').textContent=state.score;$('bestScore').textContent=state.best;$('level').textContent=state.level;$('combo').textContent=`x${state.combo}`;$('timer').textContent=Math.max(0,state.time);$('lives').textContent=state.lives;$('levelProgress').style.width=`${Math.min(100,(state.score%100))}%`}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('visible');clearTimeout(toast.id);toast.id=setTimeout(()=>el.classList.remove('visible'),1300)}
function clearPlate(){state.selected={};refresh();renderPlate()}
function serve(){if(!state.started||state.over)return;if(GROUPS.some(g=>!state.selected[g])){toast('Choose all ingredients first!');tone(180,.12,'sawtooth',.04);return}const correct=GROUPS.every(g=>state.selected[g]===state.order[g]);if(correct){const points=10+state.level*3+state.combo*2;state.score+=points;state.combo++;state.time=Math.min(75,state.time+2);tone(660,.1,'triangle',.03);setTimeout(()=>tone(880,.14,'triangle',.03),100);toast(`Perfect! +${points} points`);if(state.score>=state.level*100){state.level++;state.time=Math.min(75,state.time+5);toast(`Level ${state.level}! Faster service!`)}}else{state.lives--;state.combo=1;state.time=Math.max(0,state.time-6);tone(160,.2,'sawtooth',.04);toast('Wrong order! -1 life')}clearPlate();state.customerIndex++;state.order=newOrder();renderCustomer();hud();if(state.lives<=0||state.time<=0)endGame()}
function endGame(){state.over=true;state.started=false;clearInterval(state.timer);stopMusic();const isNew=state.score>state.best;if(isNew){state.best=state.score;localStorage.setItem('paniPuriBest',state.best)}$('finalScore').textContent=state.score;$('newBestMessage').classList.toggle('hidden',!isNew);$('gameOverOverlay').classList.remove('hidden');tone(220,.15,'square',.04);setTimeout(()=>tone(150,.2,'square',.04),160)}
function begin(){audioReady();state.score=0;state.level=1;state.combo=1;livesReset();state.time=60;state.selected={};state.customerIndex=0;state.order=newOrder();state.started=true;state.over=false;$('startOverlay').classList.add('hidden');$('gameOverOverlay').classList.add('hidden');$('serveBtn').disabled=false;$('clearBtn').disabled=false;clearPlate();renderCustomer();hud();clearInterval(state.timer);state.timer=setInterval(()=>{if(!state.started)return;state.time--;hud();if(state.time<=0)endGame()},1000);musicLoop()}
function livesReset(){state.lives=3}
function restart(){clearInterval(state.timer);state.started=false;state.over=false;state.order=null;state.selected={};$('splashOverlay').classList.remove('hidden');$('startOverlay').classList.add('hidden');$('gameOverOverlay').classList.add('hidden');$('customerCard').innerHTML='<div class="avatar">😄</div><h3>Ready to start?</h3><div class="order-list placeholder-list"><span class="placeholder-order">Press start to begin</span></div>';$('speechBubble').textContent='I am hungry for pani puri!';clearPlate();hud();stopMusic()}
$('continueBtn').onclick=()=>{$('splashOverlay').classList.add('hidden');$('startOverlay').classList.remove('hidden');tone(440,.07,'triangle',.02)};$('serveBtn').onclick=serve;$('clearBtn').onclick=()=>{if(state.started&&!state.over){clearPlate();tone(440,.07,'triangle',.02)}};$('startBtn').onclick=begin;$('playAgainBtn').onclick=begin;$('restartBtn').onclick=restart;$('soundBtn').onclick=()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊 Sound On':'🔇 Sound Off';if(state.sound)tone(440,.08,'triangle',.02)};$('musicBtn').onclick=()=>{state.music=!state.music;$('musicBtn').textContent=state.music?'🎵 Music On':'🎵 Music Off';if(state.music&&state.started)musicLoop();else stopMusic()};$('fullscreenBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};buildIngredients();$('bestScore').textContent=state.best;hud();renderPlate();
